name: Manually Triggered
on:
    workflow_dispatch:
      inputs: 
        string:
            description: A String input
            type: string
            required: true
            default: "Default Value"

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: echo $GITHUB_REF