name: Working Dirs & Shell
on: [push]

defaults:
    run:
        shell: bash
jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name: Display Working Directory & List Files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh 
                #overriding the default bash to powershell
        steps:
            - name: Display Working Directory & List Files for Windows
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
                
